name=DFRobot_PeristalticPump_V2
version=1.0.0
author=DFRobot
maintainer=JiaLi <zhixin.liu@dfrobot.com>
sentence=DFRobot Peristaltic Pump with Servo and ESP32Servo.
paragraph=Compatible with Arduino and ESP32. Supports timed run, flow-rate calibration in EEPROM, and fixed-volume pumping.
category=Device Control
url=https://github.com/DFRobot/DFRobot_PeristalticPump_V2
architectures=*
depends=ESP32Servo
